### 넘파이 임포트

In [1]:
import numpy as np

### ndarray

리스트를 넘파이의 ndarray 객체로 변환해보세요.  
data = [1, 2, 3]

In [6]:
data = [1, 2, 3]
print('data type : ', type(data))

data = np.array(data)
print('data type : ', type(data))

data type :  <class 'list'>
data type :  <class 'numpy.ndarray'>


### arange

0부터 99까지의 정수가 저장된 ndarray 객체를 만들어보세요.

In [8]:
np.arange(0, 100)

#답지에서 제시한 답: np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### 실수 range

0부터 1까지 0.1 간격으로 구성된 ndarray를 생성해보세요. 1은 포함되지 않습니다.



In [13]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### reshape

리스트에는 6개의 데이터가 저장돼 있습니다.
data = [0, 1, 2, 3, 4, 5]


다음의 2차원 ndarray 1차원 ndarray로 변환하세요.  

arr = np.array([  
    [0, 1, 2],  
    [3, 4, 5]  
])

In [14]:
arr = np.array([  
    [0, 1, 2],  
    [3, 4, 5]  
])


ValueError: cannot reshape array of size 6 into shape (1,1)

In [16]:
re = arr.reshape(1, 6)

#reshape(6)말고 flatten() 함수를 이용해서 1차원으로 변환 가능

#flatten()은 numpy에서 제공하는 다차원 배열 공간을 1차원으로 평탄화해주는 함수입니다.

re

array([[0, 1, 2, 3, 4, 5]])

In [19]:
arr = np.arange(3)

change = arr.reshape(3, 1)

change

array([[0],
       [1],
       [2]])