In [2]:
import numpy as np

### 2차원 배열

다음과 같이 2차원 ndarray 객체를 정의하세요.  

[[0 1 2]  
&nbsp;[ 3 4 5]]

In [3]:
np.array[2, 3]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [5]:
# 위키독스에서 제시한 정답

data = [
    [0, 1, 2],
    [3, 4, 5]
]
arr = np.array(data)

arr

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
np.arange(6).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

### ones

1이 20개 저장된 아래의 ndarray 객체를 만들어보세요.

In [7]:
# 위키독스에서 제시한 정답1

data = [1] * 20
np.array(data)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
#위키독스에서 제시한 정답2

np.ones(20, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

4행 5열로 저장된 아래의 ndarray 객체를 만들어 보세요.  
[[1 1 1 1 1]  
 [1 1 1 1 1]  
 [1 1 1 1 1]  
 [1 1 1 1 1]]

In [10]:
np.ones(20, dtype = int).reshape(4, 5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

255로 채워진 10X10크기의 ndarray 객체를 생성하세요.

In [12]:
# 못 풀어서 위키독스에서 제시해준 답 적음

arr = np.ones(100, dtype=int).reshape(10, 10)
arr = arr * 255

arr

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

### zeros

3x4 (행x열) 크기의 0으로 채워진 배열을 생성해보세요.

In [13]:
arr = np.zeros(12, dtype=int).reshape(3, 4) 
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### dtype

[1, 2, 3]을 np.int32 타입의 ndarray 배열로 생성하세요.

In [23]:
data = np.array([1, 2, 3], dtype='int32')

data

array([1, 2, 3])

다음 배열의 데이터 타입을 확인해보세요.

In [26]:
#위키독스에서 제시한 답
print(data.dtype)

int32


다음 데이터를 np.int16 타입의 배열로 형번환하세요.

arr = np.array([1, 2, 3])

In [28]:
arr = np.array([1, 2, 3])

arr = arr.astype(np.int16)

arr

array([1, 2, 3], dtype=int16)