### astype

arr 배열은 flopat64 타입입니다. 이를 np.int32 타입으로 변경하세요.

import numpy as np  
  
arr = np.array([1.1, 2.1, 3.1])  
arr

In [8]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])
arr

array([1.1, 2.1, 3.1])

In [6]:
arr = arr.astype(np.int32)
arr

array([1, 2, 3])

In [7]:
print(arr.dtype)

int32


### linspace

0 ~ 10 사이를 구간을 20개의 포인트로 분활한 결과를 ndarray로 표현하라.

In [10]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### 로우 인덱싱

다음의 ndarray 객체에서 마지막 로우 [6, 7, 8]을 출력하세요.

In [27]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
#내가 작성한 답
arr[2:3, 0:3]

array([[6, 7, 8]])

In [28]:
#위키독스에서 제시한 답
arr[2]

array([6, 7, 8])

### 컬럼 인덱싱

다음의 ndarray 객체에서 두 번째 [1, 4, 7]을 출력하세요.

In [29]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
#내가 제시한 답
arr[0:3, 1:2]

array([[1],
       [4],
       [7]])

In [30]:
#위키독스에서 제시한 답
arr[:,1]

array([1, 4, 7])

### 데이터 인덱싱

다음의 ndarray 객체에서 17을 선택하는 코드를 작성하라.

In [32]:
arr = np.arange(25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr[3:4, 2:3]

array([[17]])

In [34]:
#위키독스에서 제시한 답
arr[3][2] # 방법1
arr[3, 2] # 방법2 <- 한번에 인덱싱해서 성능측면에서 유리

17

### 슬라이싱

[1 3]을 슬라이싱 하는 코드를 작성하세요.

In [35]:
arr = np.arange(5)

arr

array([0, 1, 2, 3, 4])

In [40]:
arr[1, 3]
#위키독스에서 제시한 답
arr[[1, 3]]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### 슬라이싱

[6 7 8 9]를 슬라이싱 하는 코드를 작성하세요.

In [41]:
arr = np.arange(25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
arr[1:2, [1, 2, 3, 4]]

array([[6, 7, 8, 9]])

In [50]:
#위키독스에서 제시한 답

arr[1][1:]
arr[1, 1:] #한 번에 슬라이싱하는 것이 성능 측면에서 유리합니다.

array([6, 7, 8, 9])

### 슬라이싱

첫번째와 두번째 컬럼을 슬라이싱하는 코드를 작성하세요.

In [52]:
arr = np.arange(25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
# 위키백과에서 제시한 답

arr[:, 0:2] # 콤마를 기준으로 앞에는 행에 대한 정보를 뒤에는 열에 대한 정보를 입력합니다. 전체 행에 대해서 두개의 칼럼을 슬라이싱합니다.

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

### 슬라이싱

6, 7, 11, 12를 2x2 ndarray로 슬라이싱하는 코드를 작성하세요.

In [58]:
arr = np.arange(25).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
arr[1:3 , 1:3]

array([[ 6,  7],
       [11, 12]])