### ndarray 곱셈

전체 데이터에 10을 곱한 결과를 ndarray에 저장하세요.

data = [1, 2, 3]

In [2]:
#내 정답:

import numpy as np

data = np.array([1, 2, 3])
data = data * 10
data

array([10, 20, 30])

In [7]:
#위키독스에서 제시한 답:

data = np.array([1, 2, 3])
result = np.array(data) * 10
print(result)

[10 20 30]


### ndarray 제곱

전체 데이터에 제곰한 결과를 ndarray에 저장하세요.

data = [1, 2, 3]

In [9]:
data = np.array([1, 2, 3])
data ** 2

array([1, 4, 9], dtype=int32)

### ndarray 루트

전체 데이터에 루트를 적용한 결과를 ndarray에 저장하세요.

data = [1, 2, 3]

In [5]:
data = np.array([1, 2, 3])
data = np.sqrt(data)

data

array([1.        , 1.41421356, 1.73205081])

### ndarray 컬럼 평균

다음 ndarray에는 중간고사의 국어점수(10), 영어점수(20), 기말고사의 국어점수(14), 영어점수(16)이 저장돼 있습니다.

In [3]:
score = np.array([
    [10 ,20], #중간고사
    [14, 16] #기말고사
])

과목별 평균 점수를 출력하세요.

In [6]:
#위키독스에서 제시한 답
score.mean(axis=0)

#axis=0은 행 방향으로 동작합니다.
#axis=1은 열 방향으로 동작합니다.

array([12., 18.])

### ndarray 로우 표준편차

다음 ndarray에는 중간고사의 국어점수(10), 영어점수(20), 기말고사의 국어점수(14), 영어점수(16)이 저장돼 있습니다.

In [7]:
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])

중간고사와 기말고사의 표준편차를 출력하세요.

In [11]:
np.std(score, axis=1)

array([5., 1.])

### 행렬곱

두 행렬의 곱셈결과를 출력하세요.

In [19]:
a = np.arange(4).reshape(2, 2)
a

array([[0, 1],
       [2, 3]])

In [20]:
b = np.arange(1, 5).reshape(2, 2)
b

array([[1, 2],
       [3, 4]])

In [22]:
a * b

array([[ 0,  2],
       [ 6, 12]])

In [24]:
#위키독스에서 제시한 답:
np.matmul(a, b)
a @ b

array([[ 3,  4],
       [11, 16]])

### 전치행렬

다음의 ndarray로 행과 열의 위치를 바꾼 전치행렬을 출력하세요.

arr = np.arange(9).reshape(3, 3)

In [27]:
arr = np.arange(9).reshape(3, 3)

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
np.transpose(arr)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [30]:
#위키독스에서 제시한 답

arr.T
arr.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

### 짝수 배열

다음 배열에서 짝수 값만 추출하세요.

In [31]:
arr = np.arange(10)

In [32]:
arr[arr % 2 == 0]

array([0, 2, 4, 6, 8])

### 홀수 배열

다음 배열에서 짝수 값만 추출하세요.

In [33]:
arr = np.arange(10)
arr[arr % 2 != 0]

array([1, 3, 5, 7, 9])

### 여러 조건

다음 배열에서 3보다 크고 7보다 작은수만 추출하세요

 arr = np.arange(10)

In [40]:
arr = np.arange(10)
arr[arr > 3 & arr < 7]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [42]:
#위키돇,에서 제시한 답
arr = np.arange(10)
arr[(arr > 3) & (arr < 7)]

array([4, 5, 6])