### 조건에 맞는 원소값 출력

다음 ndarray 객체에서 음수를 출력하세요.

arr = np.array([-1, 2, -3, 4])

In [2]:
import numpy as np
arr = np.array([-1, 2, -3, 4])

In [5]:
arr[arr < 0]

array([-1, -3])

### 조건에 맞는 원소값 변경

다음 ndarray 객체에서 음수를 0으로 치환하세요

In [6]:
arr[arr < 0 ] = 0

In [7]:
arr

array([0, 2, 0, 4])

### 조건에 맞는 원소값 변경

다음 ndarray 객체에서 양수 혹은 0이면 10을 더하고 음수는 10을 빼세요.

arr = np.array([-1, 2, -3, 4])

In [16]:
#위키독스에서 제시한 답

arr = np.array([-1, 2, -3, 4])
negative_cond = arr < 0
positive_cond = arr >= 0
arr[negative_cond] = arr[negative_cond] - 10
arr[positive_cond] = arr[positive_cond] + 10 

print(arr[negative_cond])
print(arr[positive_cond])

[-11 -13]
[12 14]


where 함수를 사용하면 코드가 간단해 집니다.

In [10]:
 np.where(arr >= 0, arr + 10, arr - 10)

array([-21,  22, -23,  24])

### shuffle

numpy random 모듈의 shuffle 함수를 사용해서 입력 리스트의 원소들을 랜덤하게 섞어 보세요.

arr = [1, 2, 3, 4, 5]

In [11]:
arr = [1, 2, 3, 4, 5]

In [28]:
np.random.shuffle(arr)

arr

array([1, 2, 4, 3, 5])

### argmin

다음 넘파이 배열에서 최솟값의 인덱스를 출력하세요.

import numpy as np  
arr = np.array([1, 2, 3, 4, 5])

In [32]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

arr = np.argmin(arr)
arr

0

### argmax

다음 넘파일 배열에서 최댓값의 인덱스를 출력하세요

import numpy as np  
arr = np.array([1, 2, 3, 4, 5])

In [33]:
arr = np.array([1, 2, 3, 4, 5])

arr = np.argmax(arr)
arr

4

### 정렬

다음 넘파이 배열을 오름차순 정렬해보세요.

import numpy as np  
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [35]:
import numpy as np
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

arr.sort()
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

### numpy.vstack

numpy.vstack 함수를 사용하여 다음 2차원 배열을 생성하세요.

arr1 = np.array([1, 2])  
arr2 = np.array([3, 4])

결과:  
array([[1, 2],  
&nbsp;&nbsp;&nbsp;&nbsp;[3, 4]])
       


In [36]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

arr3 = np.vstack((arr1, arr2))
print(arr3)

[[1 2]
 [3 4]]


### flatten

flatten 메서드를 사용하여 다음 배열을 1차원 배열로 변경하세요.

In [41]:
import numpy as np
arr = np.array([ [1, 2], [3, 4] ])

arr.flatten()

array([1, 2, 3, 4])